/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CalendarPicker: typeof import('./src/components/MyCalendar/CalendarPicker.vue')['default']
    InputEntry: typeof import('./src/components/MyCalendar/InputEntry.vue')['default']
    MyCalendar: typeof import('./src/components/MyCalendar/MyCalendar.vue')['default']
    RecordViewer: typeof import('./src/components/MyCalendar/RecordViewer.vue')['default']
    UButton: typeof import('uview-pro/components/u-button/u-button.vue')['default']
    UIcon: typeof import('uview-pro/components/u-icon/u-icon.vue')['default']
    UInput: typeof import('uview-pro/components/u-input/u-input.vue')['default']
    URadio: typeof import('uview-pro/components/u-radio/u-radio.vue')['default']
    URadioGroup: typeof import('uview-pro/components/u-radio-group/u-radio-group.vue')['default']
  }
}
